# -*- coding: utf-8 -*-
"""Copy of Sample ML Submission Template.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cpz-t-iFWEMUWGVHdriuIi3uG8GLejss

# **Project Name**    - Wine Quality Index

##### **Project Type**    - EDA/Regression/Classification/Unsupervised
##### **Contribution**    - Individual/Team
##### **Team Member 1 - Shubham Goyal**
##### **Team Member 2 - Sidharth Sharma**
##### **Team Member 3 - Sonali**
##### **Team Member 4 - Surbhi Garg**

# **Project Summary -**

This datasets is related to red variants of the Portuguese "Vinho Verde" wine.The dataset describes the amount of various chemicals present in wine and their effect on it's quality. The datasets can be viewed as classification or regression tasks. The classes are ordered and not balanced (e.g. there are much more normal wines than excellent or poor ones).

From the EDA performed we found that

The elements with highes effect on wine
  1.Alcohol
  2.Sulphates
  3.Volatile acidity

The elements with lessest effect on quality of wine
  1.Fixed acidity
  2.Free sulphur dioxide
  3.Total suphur dioxide
  4.citric acid
  5.residual sugar
  6.chlorides
  7.density
  8.pH

# **GitHub Link -**

[Click Here](https://github.com/shubham-goyal-0811/Aiml-WineQt)

# **Problem Statement**

**This datasets is related to red variants of the Portuguese "Vinho Verde" wine.The dataset describes the amount of various chemicals present in wine and their effect on it's quality. The datasets can be viewed as classification or regression tasks. The classes are ordered and not balanced (e.g. there are much more normal wines than excellent or poor ones).Your task is to predict the quality of wine using the given data.

A simple yet challenging project, to anticipate the quality of wine.
The complexity arises due to the fact that the dataset has fewer samples, & is highly imbalanced.
Can you overcome these obstacles & build a good predictive model to classify them?**

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 15 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]





6. You may add more ml algorithms for model creation. Make sure for each and every algorithm, the following format should be answered.


*   Explain the ML Model used and it's performance using Evaluation metric Score Chart.


*   Cross- Validation & Hyperparameter Tuning

*   Have you seen any improvement? Note down the improvement with updates Evaluation metric Score Chart.

*   Explain each evaluation metric's indication towards business and the business impact pf the ML model used.

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
# Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
from plotly.subplots import make_subplots
import plotly.graph_objects as go

"""### Dataset Loading"""

# Load Dataset
from google.colab import drive
drive.mount('/content/drive/')
df = pd.read_csv('/content/drive/My Drive/WineQT.csv')

# from google.colab import drive
# drive.mount('/content/drive')

"""### Dataset First View"""

# Dataset First Look
df.sample(15)

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count

df.shape   #It tells the number of rows and coloumn

"""### Dataset Information"""

# Dataset Info

df.info()

df.columns

df.head()

df.tail()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
duplicate_count = df.duplicated().sum()

duplicate_count

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
null_values = df.isnull().sum().reset_index()
null_values

# Visualizing the missing values
#we cant do that because there are no missing values but just to be sure we can make a heatmap where white spots will indicte the missing values
plt.figure(figsize = (10,7))
sns.heatmap(df.isnull(), cbar=False)

"""### What did you know about your dataset?

I find out that my dataset has 1143 rows and 12 columns of numerical data of datatype integer or float in which we have 0 null values and 0 duplicate values

## ***2. Understanding Your Variables***
"""

# Dataset Columns
df.columns

# Dataset Describe
df.describe()

"""### Variables Description

As mentioned earlier our dataset has 12 columns of float64 datatype. 10 columns sum up to give a quality index of the wine ranging from 0 to 10.
In the data the minimum quality of wine is 3.00 and maxium is 8.00.

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
unique_values = df.nunique()
unique_values

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.
#Since there are no null values in the data so my data is already ready to be worked upon

df= df.drop('Id',axis=1)

"""### What all manipulations have you done and insights you found?

*Deleted the unwanted column of ID*

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

# Chart - 1 visualization code
columns_to_plot = df.columns.difference(['quality'])
# Calculate the number of rows and columns for subplots
num_cols =3 #number of col require in each row
num_rows = (len(columns_to_plot) + num_cols - 1) // num_cols


# Create subplots
fig, axes = plt.subplots(num_rows, num_cols, figsize=(15, 15))


# Flatten the axes array if it's a multi-dimensional array
axes = axes.flatten()


# Plot each scatter plot
for i, column in enumerate(columns_to_plot):
    row_idx = i // num_cols
    col_idx = i % num_cols

    axes[i].scatter(df[column], df['quality'], alpha=0.5)
    axes[i].set_xlabel(column)
    axes[i].set_ylabel('Quality')
    axes[i].set_title(f'Scatter Plot: {column} vs Quality')

for j in range(len(columns_to_plot), num_rows * num_cols):
    fig.delaxes(axes[j])

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

"""##### 1. Why did you pick the specific chart?

to get how each column affect the  quality of wine

##### 2. What is/are the insight(s) found from the chart?

positive correlation between alcohol content and wine quality but the dots are quite scattered indicating there is no linear relation between them and similar trend can be observed by other columns as well.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

With this we can find out how variours ingredients affect the quality of wine and thus helping to improve the overall quality of wine.

#### Chart - 2
"""

# Chart - 2 visualization code
plt.scatter(y=df['fixed acidity'],x=df['pH'],alpha = 0.7)
plt.ylabel('fixed acidity')
plt.xlabel('pH')
plt.title('fixed acidity vs pH')
plt.show()
sns.scatterplot(data=df,y='fixed acidity',x='pH')
plt.show()

"""##### 1. Why did you pick the specific chart?

To know about the correlation between fixed acidity and pH. And we are using seaborn to have better aesthetics and get a better understanding about the data.

##### 2. What is/are the insight(s) found from the chart?

*There is negative correlation between them*

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

In wine, fixed acidity and pH are closely related. As fixed acidity increases, the pH of the wine tends to decrease, making the wine more acidic. Conversely, as fixed acidity decreases, the pH tends to increase, making the wine less acidic

#### Chart - 3
"""

# Chart - 3 visualization code
sns.scatterplot(data=df,x='fixed acidity',y='citric acid',hue='pH')
plt.show()

"""##### 1. Why did you pick the specific chart?

To find out the correlation between them and to get the idea about how my pH is changing with the amount of citric acid.

##### 2. What is/are the insight(s) found from the chart?

there is a positive correlation between them

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

As the fixed acidity increased there will be more presence of citic acid.
If the fixed acidity of a solution, such as wine, is increased, it can lead to a more tart or sour taste.

#### Chart - 4
"""

# Chart - 4 visualization code
input_columns = df.columns[:-1].tolist()  # Exclude the last column

# Set up subplots
num_columns = len(input_columns)
num_rows = (num_columns + 1) // 2

fig, axes = plt.subplots(nrows=num_rows, ncols=3, figsize=(10, 20))
axes = axes.flatten()

# Plot box plots for each selected variable
for i, column in enumerate(input_columns):
    #showfliers=False agar outliers nhi dikhane mujhe
    sns.boxplot(x=df[column], ax=axes[i])
    axes[i].set_title(column)
    axes[i].set_xticks([])  # Remove existing x-axis ticks
    axes[i].set_xticklabels([])  # Remove existing x-axis tick labels
    axes[i].tick_params(axis='x', rotation=90)  # Set the rotation angle

# Remove empty subplots, if any
for j in range(num_columns, num_rows * 2):
    fig.delaxes(axes[j])

# Adjust layout
plt.tight_layout()
plt.show()

"""##### 1. Why did you pick the specific chart?

Box plot gives me best idea for outliers.

##### 2. What is/are the insight(s) found from the chart?

1. Median of fixed acidity increases with increasing quality rating, whereas volatile acidity decreases.
2. median of the amount of citric acid increases with increasing quality rating.
3. residual sugar, chlorides and density seem to have little effect on quality rating.
4. low and high rated wines seem to be low in free sulfur dioxide and total sulfur dioxide.
5. better rated wines seem to have a lower pH.
6. wines with higher ratings seem to be higher in the amount of sulphates and alcohol.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Understanding the relationship between various features and quality can help businesses identify areas where they can optimize costs without compromising the perceived quality

#### Chart - 5
"""

num_cols = 3
num_rows = (len(df.columns) + num_cols - 1) // num_cols

# Create subplots
fig, axes = plt.subplots(num_rows, num_cols, figsize=(15, 5 * num_rows))

# Flatten the axes array if it's a multi-dimensional array
axes = axes.flatten()

# Custom colors for the histograms
histogram_colors = ['skyblue', 'salmon', 'lightgreen', 'orange', 'purple']

# Loop through each column and create a histogram
for i, column in enumerate(df.columns):
    median_value = np.median(df[column])

    # Determine the subplot index
    row_idx = i // num_cols
    col_idx = i % num_cols

    # Plot the histogram with custom color
    sns.histplot(data=df, x=df[column], kde=True, ax=axes[i], color=histogram_colors[i % len(histogram_colors)])
    axes[i].set_title(f'{median_value.round(4)} is the median value for {column}.')

# Remove any empty subplots beyond the number of valid columns
for j in range(len(df.columns), num_rows * num_cols):
    fig.delaxes(axes[j])

# Adjust layout for better spacing
plt.tight_layout()

# Show the plots
plt.show()

"""##### 1. Why did you pick the specific chart?

Because we needed to perform an univariate analysis on the data to check the skewness of the data.

##### 2. What is/are the insight(s) found from the chart?

Normal Skewed -> fixed acidity, volatile acidity,residual sugar,chlorides,density,Ph,sulphates

right skewed-> citric acid, free sulphur dioxide, total sulphur dioxide, alchohol

bimodel-> quality

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 6
"""

# Chart - 6 visualization code
average_quality = df.groupby("quality").mean()

average_quality.plot(kind="bar",figsize=(16,7))
plt.show()
# average_quality

"""##### 1. Why did you pick the specific chart?

To see quality stats

##### 2. What is/are the insight(s) found from the chart?

The chart explores links between wine features and quality. While not definitive, it suggests a possible upward trend in quality with higher alcohol content. Similar, but weaker trends, are seen with chlorides and citric acid. Remember, correlation doesn't equal causation, and more analysis is needed for a clearer picture.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

While the chart hints at links between wine features like alcohol and quality, it's not definitive. It suggests potentially better quality with higher alcohol, but other factors likely play a role. Caution is key. Overemphasizing single features or ignoring consumer preferences could backfire. Combining these insights with other knowledge and further analysis can lead to better decision-making for wine producers, potentially impacting business positively.

#### Chart - 7
"""

fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(12, 10))

# Scatter plot 1
sns.scatterplot(data=df, x=df['fixed acidity'], y='volatile acidity', hue='quality', ax=axes[0, 0], )
axes[0, 0].set_title('Fixed Acidity vs. Volatile Acidity')

# Scatter plot 2
sns.scatterplot(data=df, x='citric acid', y=df['residual sugar'], hue='quality', ax=axes[0, 1])
axes[0, 1].set_title('Citric Acid vs. Residual Sugar')

# Scatter plot 3
sns.scatterplot(x=df['free sulfur dioxide'], y=df['total sulfur dioxide'], hue=df['quality'], ax=axes[1, 0])
axes[1, 0].set_title('Free Sulfur Dioxide vs. Total Sulfur Dioxide')

# Scatter plot 4
sns.scatterplot(x=df['pH'], y=df['sulphates'], hue=df['quality'], ax=axes[1, 1])
axes[1, 1].set_title('pH vs. Sulphates')

# Adjust layout
plt.tight_layout()

# Show the plots
plt.show()

"""##### 1. Why did you pick the specific chart?

Scatter plot is suitable for analyzing two continuous variables. It indicates the linear or non-linear relationship between the variables.

##### 2. What is/are the insight(s) found from the chart?

The charts show weak positive correlations between fixed acidity and volatile acidity, and negative between citric acid and residual sugar. A strong positive correlation exists between free and total sulfur dioxide. Finally, there's a weak negative correlation between pH and sulphates. Remember, these are tendencies, not always the case.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Understanding these correlations can help in creating better wines, targeting marketing, and optimizing processes. However, relying solely on them can lead to oversimplification and misinterpretation, potentially causing negative impacts.

#### Chart - 8
"""

features=['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
           'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
           'pH', 'sulphates']

for feature in features:
    fig = plt.figure(figsize=(20, 5))
    sns.lineplot(x=df[feature], y=df['alcohol'], data=df, color='green')
    plt.title(f'{feature} vs Alcohol')
    plt.xlabel(feature)
    plt.ylabel('Alcohol')
    plt.show()

"""##### 1. Why did you pick the specific chart?

we chose this graph because we wanted to know how alchohol is depending on various aspects.

##### 2. What is/are the insight(s) found from the chart?

No insights from this graph

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

#### Chart - 9
"""

import matplotlib.pyplot as plt

# Grouping data by a categorical variable and aggregating counts for each category
grouped_data = df.groupby(['sulphates', 'alcohol']).size().unstack(fill_value=0)
grouped_data
# Plot stacked bar chart
grouped_data.plot(kind='bar', stacked=True, figsize=(10, 6))
plt.title('Stacked Bar Chart of Categories Across Different Groups')
plt.xlabel('sulphates')
plt.ylabel('Count')
plt.xticks(rotation=45)  # Rotate x-axis labels for better readability
plt.legend(title='alcohol')  # Add legend with category labels
plt.show()

"""##### 1. Why did you pick the specific chart?

to get a comprehensive overview of sulphates and count

##### 2. What is/are the insight(s) found from the chart?

The chart provides insight into the distribution of 'sulphates' and 'alcohol' levels across different categories, allowing for the identification of potential patterns or trends within the dataset.

The insights gained from the chart can inform decision-making processes related to product development, marketing strategies, or customer segmentation, potentially leading to positive business outcomes.

The insight gained from the density plot may not directly lead to a positive business impact.

#### Chart - 10
"""

# Chart import pandas as pd
import matplotlib.pyplot as plt

aggregated_data = df.groupby(['alcohol', 'quality']).size().unstack(fill_value=0)

# Plot stacked bar chart
aggregated_data.plot(kind='bar', stacked=True, figsize=(10, 6))
plt.title('Stacked Bar Chart: Composition of Categories Across Groups')
plt.xlabel('alcohol')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.legend(title='quality')
plt.show()

"""##### 1. Why did you pick the specific chart?

was chosen for its effectiveness in comparing the composition of categories across different groups

##### 2. What is/are the insight(s) found from the chart?

highlighting the distribution and relative proportions of Alchohol on Quality

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

he gained insights can potentially lead to a positive business impact by informing strategic decisions related to product offerings, target audience preferences, and marketing strategies.

#### Chart - 11
"""

# Calculate the average quality ratings for each level of 'sulphates' and 'alcohol'
avg_quality_sulphates = df.groupby('sulphates')['quality'].mean().round(2)
avg_quality_alcohol = df.groupby('alcohol')['quality'].mean().round(2)
avg_quality_alcohol=avg_quality_alcohol.reset_index()
avg_quality_alcohol['alcohol']=avg_quality_alcohol['alcohol'].round(2)
avg_quality_alcohol
avg_quality_sulphates = df.groupby('sulphates')['quality'].mean().round(2)
avg_quality_sulphates=avg_quality_sulphates.reset_index()
avg_quality_sulphates['sulphates']=avg_quality_sulphates['sulphates'].round(2)
avg_quality_sulphates

# Plotting bar plots
plt.figure(figsize=(16, 4))

# Bar plot for average quality ratings by 'sulphates'

sns.barplot(x=avg_quality_sulphates['sulphates'], y=avg_quality_sulphates['quality'],hue=avg_quality_sulphates['sulphates'], palette=sns.color_palette('magma',n_colors=avg_quality_sulphates['sulphates'].nunique()),legend=False)
plt.title('Average Quality Ratings by Sulphates')
plt.xlabel('Sulphates')
plt.ylabel('Average Quality Rating')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Bar plot for average quality ratings by 'alcohol'
plt.figure(figsize=(16, 4))
sns.barplot(x=avg_quality_alcohol['alcohol'], y=avg_quality_alcohol['quality'],hue=avg_quality_alcohol['alcohol'], palette=sns.color_palette('viridis',n_colors=avg_quality_alcohol['alcohol'].nunique()),legend=False)
plt.title('Average Quality Ratings by Alcohol')
plt.xlabel('Alcohol')
plt.ylabel('Average Quality Rating')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""##### 1. Why did you pick the specific chart?

The specific chart was chosen because a stacked bar chart effectively illustrates the composition of categories across different groups ('alcohol' levels and 'quality' ratings), allowing for a clear comparison of category distributions within each group.

##### 2. What is/are the insight(s) found from the chart?

The bar chart reveals the distribution of 'quality' ratings across different 'alcohol' levels. Insights may include the prevalence of certain quality ratings

#### Chart - 12
"""

# Chart - 12 visualization code
colors = ['#FC4F4F', '#FFBC80', '#FF9F45', '#F76E11', '#CD104D', '#820000']
quality = [3,4,5,6,7,8]
fig = make_subplots(rows = 1, cols = 2, specs = [[{"type": "pie"}, {"type": "bar"}]])
fig.add_trace(go.Pie(values = df.quality.value_counts(), labels = df.quality.value_counts().index, domain = dict(x=[0, 0.5]),
                     marker = dict(colors = colors), hole = .3, name=''), row = 1, col = 1)
fig.add_trace(go.Bar(x = df.quality.value_counts().index, y = df.quality.value_counts(), name='', marker = dict(color = quality,
                     colorscale = colors)), row = 1, col = 2)
fig.update_layout(showlegend = False)
fig.show()

"""##### 1. Why did you pick the specific chart?

to know about the distribution of data

##### 2. What is/are the insight(s) found from the chart?

1. Majority Wines are of quality index 5 followed by quality index 6
2. Quality index 3 was given to least number of wines

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The wine with a greater quality index can be priced higher and thus can be proved better in business

#### Chart - 13
"""

# Chart - 13 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code
plt.figure(figsize=(15,15))
sns.heatmap(df.corr(),linewidths=0.5,annot=True,cmap='rainbow')
plt.show()

"""##### 1. Why did you pick the specific chart?

To find correlation

##### 2. What is/are the insight(s) found from the chart?

The chart hints at connections between specific wine features like alcohol content and potentially higher quality. While alcohol appears linked to better quality, the data is scattered, suggesting other factors likely play a role. It's important to remember that correlation doesn't equal causation. Focusing solely on individual aspects could be misleading.

#### Chart - 15 - Pair Plot
"""

# Pair Plot visualization code
sns.pairplot(df,palette="bright", hue='quality')
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

***OUTCOMES***

The elements with highes effect on wine
  1.Alcohol
  2.Sulphates
  3.Volatile acidity

The elements with lessest effect on quality of wine
  1.Fixed acidity
  2.Free sulphur dioxide
  3.Total suphur dioxide
  4.citric acid
  5.residual sugar
  6.chlorides
  7.density
  8.pH

## ***5. Hypothesis Testing***

### Based on your chart experiments, define three hypothetical statements from the dataset. In the next three questions, perform hypothesis testing to obtain final conclusion about the statements through your code and statistical testing.

Answer Here.

### Hypothetical Statement - 1

#### 1. State Your research hypothesis as a null hypothesis and alternate hypothesis.

Answer Here.

#### 2. Perform an appropriate statistical test.
"""

# Perform Statistical Test to obtain P-Value

"""##### Which statistical test have you done to obtain P-Value?

Answer Here.

##### Why did you choose the specific statistical test?

Answer Here.

### Hypothetical Statement - 2

#### 1. State Your research hypothesis as a null hypothesis and alternate hypothesis.

Answer Here.

#### 2. Perform an appropriate statistical test.
"""

# Perform Statistical Test to obtain P-Value

"""##### Which statistical test have you done to obtain P-Value?

Answer Here.

##### Why did you choose the specific statistical test?

Answer Here.

### Hypothetical Statement - 3

#### 1. State Your research hypothesis as a null hypothesis and alternate hypothesis.

Answer Here.

#### 2. Perform an appropriate statistical test.
"""

# Perform Statistical Test to obtain P-Value

"""##### Which statistical test have you done to obtain P-Value?

Answer Here.

##### Why did you choose the specific statistical test?

Answer Here.

## ***6. Feature Engineering & Data Pre-processing***

### 1. Handling Missing Values
"""

# Handling Missing Values & Missing Value Imputation

"""#### What all missing value imputation techniques have you used and why did you use those techniques?

Answer Here.

### 2. Handling Outliers
"""

# Handling Outliers & Outlier treatments

"""##### What all outlier treatment techniques have you used and why did you use those techniques?

Answer Here.

### 3. Categorical Encoding
"""

# Encode your categorical columns

"""#### What all categorical encoding techniques have you used & why did you use those techniques?

Answer Here.

### 4. Textual Data Preprocessing
(It's mandatory for textual dataset i.e., NLP, Sentiment Analysis, Text Clustering etc.)

#### 1. Expand Contraction
"""

# Expand Contraction

"""#### 2. Lower Casing"""

# Lower Casing

"""#### 3. Removing Punctuations"""

# Remove Punctuations

"""#### 4. Removing URLs & Removing words and digits contain digits."""

# Remove URLs & Remove words and digits contain digits

"""#### 5. Removing Stopwords & Removing White spaces"""

# Remove Stopwords

# Remove White spaces

"""#### 6. Rephrase Text"""

# Rephrase Text

"""#### 7. Tokenization"""

# Tokenization

"""#### 8. Text Normalization"""

# Normalizing Text (i.e., Stemming, Lemmatization etc.)

"""##### Which text normalization technique have you used and why?

Answer Here.

#### 9. Part of speech tagging
"""

# POS Taging

"""#### 10. Text Vectorization"""

# Vectorizing Text

"""##### Which text vectorization technique have you used and why?

Answer Here.

### 4. Feature Manipulation & Selection

#### 1. Feature Manipulation
"""

# Manipulate Features to minimize feature correlation and create new features

"""#### 2. Feature Selection"""

# Select your features wisely to avoid overfitting

"""##### What all feature selection methods have you used  and why?

Answer Here.

##### Which all features you found important and why?

Answer Here.

### 5. Data Transformation

#### Do you think that your data needs to be transformed? If yes, which transformation have you used. Explain Why?
"""

# Transform Your data

"""### 6. Data Scaling"""

# Scaling your data

"""##### Which method have you used to scale you data and why?

### 7. Dimesionality Reduction

##### Do you think that dimensionality reduction is needed? Explain Why?

Answer Here.
"""

# DImensionality Reduction (If needed)

"""##### Which dimensionality reduction technique have you used and why? (If dimensionality reduction done on dataset.)

Answer Here.

### 8. Data Splitting
"""

# Split your data to train and test. Choose Splitting ratio wisely.

"""##### What data splitting ratio have you used and why?

Answer Here.

### 9. Handling Imbalanced Dataset

##### Do you think the dataset is imbalanced? Explain Why.

Answer Here.
"""

# Handling Imbalanced Dataset (If needed)

"""##### What technique did you use to handle the imbalance dataset and why? (If needed to be balanced)

Answer Here.

## ***7. ML Model Implementation***

### ML Model - 1
"""

# ML Model - 1 Implementation

# Fit the Algorithm

# Predict on the model

"""#### 1. Explain the ML Model used and it's performance using Evaluation metric Score Chart."""

# Visualizing evaluation Metric Score chart

"""#### 2. Cross- Validation & Hyperparameter Tuning"""

# ML Model - 1 Implementation with hyperparameter optimization techniques (i.e., GridSearch CV, RandomSearch CV, Bayesian Optimization etc.)

# Fit the Algorithm

# Predict on the model

"""##### Which hyperparameter optimization technique have you used and why?

Answer Here.

##### Have you seen any improvement? Note down the improvement with updates Evaluation metric Score Chart.

Answer Here.

### ML Model - 2

#### 1. Explain the ML Model used and it's performance using Evaluation metric Score Chart.
"""

# Visualizing evaluation Metric Score chart

"""#### 2. Cross- Validation & Hyperparameter Tuning"""

# ML Model - 1 Implementation with hyperparameter optimization techniques (i.e., GridSearch CV, RandomSearch CV, Bayesian Optimization etc.)

# Fit the Algorithm

# Predict on the model

"""##### Which hyperparameter optimization technique have you used and why?

Answer Here.

##### Have you seen any improvement? Note down the improvement with updates Evaluation metric Score Chart.

Answer Here.

#### 3. Explain each evaluation metric's indication towards business and the business impact pf the ML model used.

Answer Here.

### ML Model - 3
"""

# ML Model - 3 Implementation

# Fit the Algorithm

# Predict on the model

"""#### 1. Explain the ML Model used and it's performance using Evaluation metric Score Chart."""

# Visualizing evaluation Metric Score chart

"""#### 2. Cross- Validation & Hyperparameter Tuning"""

# ML Model - 3 Implementation with hyperparameter optimization techniques (i.e., GridSearch CV, RandomSearch CV, Bayesian Optimization etc.)

# Fit the Algorithm

# Predict on the model

"""##### Which hyperparameter optimization technique have you used and why?

Answer Here.

##### Have you seen any improvement? Note down the improvement with updates Evaluation metric Score Chart.

Answer Here.

### 1. Which Evaluation metrics did you consider for a positive business impact and why?

Answer Here.

### 2. Which ML model did you choose from the above created models as your final prediction model and why?

Answer Here.

### 3. Explain the model which you have used and the feature importance using any model explainability tool?

Answer Here.

## ***8.*** ***Future Work (Optional)***

### 1. Save the best performing ml model in a pickle file or joblib file format for deployment process.
"""

# Save the File

"""### 2. Again Load the saved model file and try to predict unseen data for a sanity check.

"""

# Load the File and predict unseen data.

"""### ***Congrats! Your model is successfully created and ready for deployment on a live server for a real user interaction !!!***

# **Conclusion**

Write the conclusion here.

### ***Hurrah! You have successfully completed your Machine Learning Capstone Project !!!***
"""